im1 = imread('../data/NewBackGround.jpg');
im2 = imread('../data/BearInWater.jpg');

figure('Units', 'pixel', 'Position',...
    [100,100,1000,700], 'toolbar', 'none');

subplot(121);
imshow(im2);
title({'Foreground',...
    'press red tool button to mark polygon as copying region'});

subplot(122);
himg = imshow(im1);
title({'Background',...
    'press blue tool button to compute blended image'});

hpolys = [];

hToolMark = uipushtool(...
    'CData', reshape(repmat([1 0 0], 100, 1), [10 10 3]),...
    'TooltipString', 'define copying region on the foreground image',...
    'ClickedCallback', @toolMarkCB);

hToolWarp = uipushtool(...
    'CData', reshape(repmat([1 0 1], 100, 1), [10 10 3]),...
    'TooltipString', 'compute blended image',...
    'ClickedCallback', @(src, evt)toolPasteCB(false));

hToolWarpMix = uipushtool(...
    'CData', reshape(repmat([0 1 1], 100, 1), [10 10 3]),...
    'TooltipString', 'compute blended image with mixing gradients',...
    'ClickedCallback', @(src, evt)toolPasteCB(true));

hToolShowROI = uipushtool(...
    'CData', reshape(repmat([0 0 1], 100, 1), [10 10 3]),...
    'TooltipString', 'Show ROI polygon',...
    'ClickedCallback', @(src, evt) showROICB());

hToolHideROI = uipushtool(...
    'CData', reshape(repmat([0 0 1], 100, 1), [10 10 3]),...
    'TooltipString', 'Show ROI polygon',...
    'ClickedCallback', @(src, evt) hideROICB());

hToolSave = uipushtool(...
    'CData', reshape(repmat([0 1 0], 100, 1), [10 10 3]),...
    'TooltipString', 'save blended image to file',...
    'ClickedCallback', @toolSaveCB);

function showROICB()
    hpolys = evalin('base', 'hpolys');
    if length(hpolys) >= 2
        set(hpolys(2), 'Visible', 'on');
    end
end

function hideROICB()
    hpolys = evalin('base', 'hpolys');
    if length(hpolys) >= 2
        set(hpolys(2), 'Visible', 'off');
    end
end
